name: kotlin
version: 7.4.2
schema: 1
scm: github.com/pubnub/kotlin
files:
  - build/libs/pubnub-kotlin-7.4.2-all.jar
sdks:
  - 
      type: library
      full-name: Kotlin SDK
      short-name: Kotlin
      artifacts:
        -
          language: kotlin
          tags:
            - Server
            - Mobile
          source-repository: https://github.com/pubnub/kotlin
          documentation: https://www.pubnub.com/docs/sdks/kotlin/
          tier: 2
          artifact-type: library
          distributions:
            -
              distribution-type: library
              distribution-repository: maven
              package-name: pubnub-kotlin-7.4.2
              location: https://repo.maven.apache.org/maven2/com/pubnub/pubnub-kotlin/7.4.2/pubnub-kotlin-7.4.2.jar
              supported-platforms:
                supported-operating-systems:
                  Android:
                    runtime-version:
                      - ART
                    target-api-level: 
                      - 23
                    minimum-api-level:
                      - 23
                    maximum-api-level:
                      - 30  
                    target-architecture:
                      - armeabi-v7a
                      - atom
                      - armeabi
                      - arm64-v8a
                  Linux:
                    runtime-version:
                      - JVM 8 
                    minimum-os-version:
                      - Ubuntu 12.04
                    maximum-os-version:
                      - Ubuntu 20.04 LTS
                    target-architecture:
                      - x86
                      - x86-64
                  macOS:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - macOS 10.12
                    maximum-os-version:
                      - macOS 11.0.1
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - Windows Vista Ultimate
                    maximum-os-version:
                      - Windows 10 Home
                    target-architecture:
                      - x86
                      - x86-64
              requires:
                -
                  name: retrofit
                  min-version: 2.9.0
                  location: https://repo.maven.apache.org/maven2/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/square/retrofit/blob/2.9.0/LICENSE.txt
                  is-required: Required
                -
                  name: okhttp
                  min-version: 3.14.9
                  location: https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/square/okhttp/blob/parent-3.14.9/LICENSE.txt
                  is-required: Required
                -
                  name: converter-gson
                  min-version: 2.9.0
                  location: https://repo.maven.apache.org/maven2/com/squareup/retrofit2/converter-gson/2.9.0/converter-gson-2.9.0.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/square/retrofit/blob/2.9.0/LICENSE.txt
                  is-required: Required
                -
                  name: gson
                  min-version: 2.8.6
                  location: https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/google/gson/blob/gson-parent-2.8.6/LICENSE
                  is-required: Required
                -
                  name: jackson-databind
                  min-version: 2.12.2
                  location: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.2/jackson-databind-2.12.2.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.12.2/README.md
                  is-required: Required
                -
                  name: jackson-module-kotlin
                  min-version: 2.12.2
                  location: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/module/jackson-module-kotlin/2.12.2/jackson-module-kotlin-2.12.2.jar
                  license: Apache License, Version 2.0
                  license-url: "" 
                  is-required: Required
                -
                  name: json
                  min-version: "20210307"
                  location: https://repo.maven.apache.org/maven2/org/json/json/20210307/json-20210307.jar
                  license: ""
                  license-url: https://github.com/stleary/JSON-java/blob/20210307/LICENSE
                  is-required: Required
changelog:
  - date: 2023-03-07
    version: v7.4.2
    changes:
      - type: bug
        text: "Remove deprecation for Grant Token methods."
      - type: bug
        text: "Update Jackson and Json libraries to avoid vulnerabilities."
  - date: 2023-02-02
    version: v7.4.1
    changes:
      - type: bug
        text: "Uploading an encrypted file correctly sets the content size in the multipart body."
  - date: 2022-09-20
    version: v7.4.0
    changes:
      - type: feature
        text: "PNFileEventResult has messageJson field with the same JsonElement type as in other events."
  - date: 2022-07-21
    version: v7.3.2
    changes:
      - type: bug
        text: "Gson, logback."
      - type: bug
        text: "Removed CREATE for space as a valid permission that can be assigned to token."
  - date: 2022-06-28
    version: v7.3.1
    changes:
      - type: bug
        text: "Renamed name to id in SpacePermissions."
  - date: 2022-06-28
    version: v7.3.0
    changes:
      - type: feature
        text: "Introduced new GrantToken method with no channel groups."
  - date: 2022-06-14
    version: v7.2.0
    changes:
      - type: feature
        text: "PNChannelMetadata and PNUUIDMetadata has status and type now."
      - type: feature
        text: "PNChannelMembership and PNMember has status now."
      - type: bug
        text: "It's possible to sort memberships and members by nested fields."
  - date: 2022-05-23
    version: v7.1.0
    changes:
      - type: feature
        text: "Upgrade okhttp library ."
  - date: 2022-04-19
    version: v7.0.1
    changes:
      - type: bug
        text: "Update Jackson library with fixes for CVE-2020-36518."
  - date: 2022-01-12
    version: v7.0.0
    changes:
      - type: improvement
        text: "BREAKING CHANGES: uuid is required parameter in PNConfiguration constructor."
  - date: 2021-12-16
    version: v6.3.0
    changes:
      - type: feature
        text: "Add revoke token feature."
  -
    version: v6.2.0
    date: 2021-10-06
    changes:
      -
        type: feature
        text: "Acceptance tests plugged into CI pipeline."
      -
        type: feature
        text: "Internal telemetry enhancement."
      -
        type: bug
        text: "Meta field exposed correctly in PNToken class."
  -
    version: v6.1.0
    date: 2021-09-08
    changes:
      -
        type: feature
        text: "Method grantToken has beed added. It allows generation of signed token with permissions for channels and channel groups."
  -
    version: v6.0.3
    date: 2021-07-26
    changes:
      -
        type: bug
        text: "Using random initialization vector according to 'useRandomInitializationVector' flag setting."
  -
    version: v6.0.2
    date: 2021-07-06
    changes:
      -
        type: bug
        text: "Handle socket exception causing crash while canceling the call."
  -
    version: v6.0.1
    date: 2021-05-25
    changes:
      -
        type: bug
        text: "There was missing PNAcknowledgmentCategory status callback after unsubscribe operation. Problem was caused by ungaught SSLException. This release provides a fix for the issue."
  -
    version: v6.0.0
    date: 2021-05-12
    changes:
      -
        type: feature
        text: "Random initialisation vector used when encryption enabled is now default behaviour."
      -
        type: feature
        text: "Bumping versions of used dependencies."
      -
        type: bug
        text: "There were some non daemon threads running in background preventing VM from exiting. Now they are daemon threads."
  -
    version: v5.1.3
    date: 2021-03-24
    changes:
      -
        type: bug
        text: "Properly canceling HTTP requests when OkHttp client 3.14.9 used."
  -
    version: v5.1.2
    date: 2021-03-09
    changes:
      -
        type: bug
        text: "In some specific timing conditions subscription loop could loose reference to one of the retrofit call and we would loose posibility to control it. In the meantime we'd start yet another subscription call. One of them is obviously not necessary Synchronization has been improved so it's no longer possible."
      -
        type: bug
        text: "It was not possible to properly cancel the OkHttp connection when Google Security Provider (ProviderInstaller) is being used."
  -
    version: v5.1.1
    date: 2021-01-20
    changes:
      -
        type: bug
        text: "File upload encryption fix."
      -
        type: bug
        text: "Asynchronous file upload encryption fix."
      -
        type: bug
        text: "Telemetry fix - removal of `putIfAbsent`."
  -
    version: v5.1.0
    date: 2020-12-16
    changes:
      -
        type: feature
        text: "Files support includes sending, downloading, listing, deleting together with notifications about file events."
      -
        type: feature
        text: "New methods can set and remove memberships/channelMembers in one call."
      -
        type: feature
        text: "New field `page` can be returned from the backend in case there's more data to fetch for the original query. This new field can be used directly in new `fetchMessages` and `getMessagesActions` method versions. The old versions in which paging information was in separate arguments has been deprecated."
      -
        type: feature
        text: "FetchMessages has a default limit of 100 for single-channel call."
      -
        type: bug
        text: "Make PNMessageActionResultevent accessible (no longer internal)."
      -
        type: bug
        text: "Method `addMemberships` has been deprecated and shouldn't be used in the future."
  -
    version: v5.0.2
    date: 2020-10-20
    changes:
      -
        type: bug
        text: "Remove Instant to improve Android version compatibility."
  -
    version: 5.1.0
    date: 2020-09-28
    changes:
      -
        type: feature
        text: "Add simplified Objects API support with UUID and Channel metadata / membership management."
      -
        type: bug
        text: "Fix crashing Telemetry Manager."
  -
    version: v5.0.0
    date: 2020-08-12
    changes:
      -
        type: improvement
        text: "PubNub methods will no longer support builder style calls and will use named arguments instead."
  - version: v4.0.1
    date: 2020-07-28
    changes:
      - type: feature
        text: kdoc (javadoc)
  - version: v4.0.0
    date: 2020-06-11
    changes:
      - type: feature
        text: Initial release
features:
  access:
    - ACCESS-GRANT
    - ACCESS-GRANT-MANAGE
    - ACCESS-GRANT-DELETE
    - ACCESS-SECRET-KEY-ALL-ACCESS
    - ACCESS-GRANT-TOKEN
    - ACCESS-PARSE-TOKEN
    - ACCESS-SET-TOKEN
    - ACCESS-REVOKE-TOKEN
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
    - PUSH-TYPE-APNS
    - PUSH-TYPE-APNS2
    - PUSH-TYPE-FCM
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-FETCH-MESSAGES
    - STORAGE-DELETE-MESSAGES
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-PUBSUB-V2
    - SUBSCRIBE-MESSAGE-ACTIONS-LISTENER
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-FILTERING
    - OBJECTS-SORTING
    - OBJECTS-GET-ALL-UUID-METADATA
    - OBJECTS-GET-UUID-METADATA
    - OBJECTS-SET-UUID-METADATA
    - OBJECTS-REMOVE-UUID-METADATA
    - OBJECTS-GET-ALL-CHANNEL-METADATA
    - OBJECTS-GET-CHANNEL-METADATA
    - OBJECTS-SET-CHANNEL-METADATA
    - OBJECTS-REMOVE-CHANNEL-METADATA
    - OBJECTS-GET-MEMBERSHIPS-V2
    - OBJECTS-SET-MEMBERSHIPS-V2
    - OBJECTS-REMOVE-MEMBERSHIPS-V2
    - OBJECTS-GET-CHANNEL-MEMBERS-V2
    - OBJECTS-SET-CHANNEL-MEMBERS-V2
    - OBJECTS-REMOVE-CHANNEL-MEMBERS-V2
    - OBJECTS-MANAGE-MEMBERSHIPS-V2
    - OBJECTS-MANAGE-CHANNEL-MEMBERS-V2
  files:
    - FILES-DELETE-FILE
    - FILES-DOWNLOAD-FILE
    - FILES-GET-FILE-URL
    - FILES-LIST-FILES
    - FILES-SEND-FILE
  unsubscribe:
    - UNSUBSCRIBE-ALL
    - UNSUBSCRIBE-SUPPRESS-LEAVE-EVENTS
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE
  others:
    - TELEMETRY
    - QUERY-PARAM
    - PN-OTHER-PROCESSING
    - CREATE-PUSH-PAYLOAD
supported-platforms:
  - version: PubNub Kotlin SDK
    platforms:
      - Windows 10 (8u51 and above)
      - Windows 8.x (Desktop)
      - Windows 7 SP1
      - Windows Vista SP2
      - Windows Server 2008 R2 SP1 (64-bit)
      - Windows Server 2012 and 2012 R2 (64-bit)
      - Intel-based Mac running Mac OS X 10.8.3+, 10.9+
      - Oracle Linux 5.5+
      - Oracle Linux 6.x
      - Oracle Linux 7.x (64-bit) (8u20 and above)
      - Red Hat Enterprise Linux 5.5+, 6.x
      - Red Hat Enterprise Linux 7.x (64-bit) (8u20 and above)
      - Suse Linux Enterprise Server 10 SP2+, 11.x
      - Suse Linux Enterprise Server 12.x (64-bit) (8u31 and above)
      - Ubuntu Linux 12.04 LTS, 13.x
      - Ubuntu Linux 14.x (8u25 and above)
      - Ubuntu Linux 15.04 (8u45 and above)
      - Ubuntu Linux 15.10 (8u65 and above)
    editors:
      - Java8+
  - version: PubNub Android SDK
    platforms:
      - Android 2.3.1+
