name: kotlin
version: 5.1.1
schema: 1
scm: github.com/pubnub/kotlin
files:
  - build/libs/pubnub-kotlin-5.1.1-all.jar
changelog:
  -
    version: v5.1.1
    date: 2021-01-20
    changes:
      -
        type: bug
        text: "File upload encryption fix."
      -
        type: bug
        text: "Asynchronous file upload encryption fix."
      -
        type: bug
        text: "Telemetry fix - removal of `putIfAbsent`."
  -
    version: v5.1.0
    date: 2020-12-16
    changes:
      -
        type: feature
        text: "Files support includes sending, downloading, listing, deleting together with notifications about file events."
      -
        type: feature
        text: "New methods can set and remove memberships/channelMembers in one call."
      -
        type: feature
        text: "New field `page` can be returned from the backend in case there's more data to fetch for the original query. This new field can be used directly in new `fetchMessages` and `getMessagesActions` method versions. The old versions in which paging information was in separate arguments has been deprecated."
      -
        type: feature
        text: "FetchMessages has a default limit of 100 for single-channel call."
      -
        type: bug
        text: "Make PNMessageActionResultevent accessible (no longer internal)."
      -
        type: bug
        text: "Method `addMemberships` has been deprecated and shouldn't be used in the future."
  -
    version: v5.0.2
    date: 2020-10-20
    changes:
      -
        type: bug
        text: "Remove Instant to improve Android version compatibility."
  -
    version: 5.1.0
    date: 2020-09-28
    changes:
      -
        type: feature
        text: "Add simplified Objects API support with UUID and Channel metadata / membership management."
      -
        type: bug
        text: "Fix crashing Telemetry Manager."
  -
    version: v5.0.0
    date: 2020-08-12
    changes:
      -
        type: improvement
        text: "PubNub methods will no longer support builder style calls and will use named arguments instead."
  - version: v4.0.1
    date: 2020-07-28
    changes:
      - type: feature
        text: kdoc (javadoc)
  - version: v4.0.0
    date: 2020-06-11
    changes:
      - type: feature
        text: Initial release
features:
  access:
    - ACCESS-GRANT
    - ACCESS-GRANT-MANAGE
    - ACCESS-GRANT-DELETE
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
    - PUSH-TYPE-APNS
    - PUSH-TYPE-APNS2
    - PUSH-TYPE-GCM
    - PUSH-TYPE-FCM
    - PUSH-TYPE-MPNS
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-FETCH-MESSAGES
    - STORAGE-DELETE-MESSAGES
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-PUBSUB-V2
    - SUBSCRIBE-MESSAGE-ACTIONS-LISTENER
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-FILTERING
    - OBJECTS-SORTING
    - OBJECTS-GET-ALL-UUID-METADATA
    - OBJECTS-GET-UUID-METADATA
    - OBJECTS-SET-UUID-METADATA
    - OBJECTS-REMOVE-UUID-METADATA
    - OBJECTS-GET-ALL-CHANNEL-METADATA
    - OBJECTS-GET-CHANNEL-METADATA
    - OBJECTS-SET-CHANNEL-METADATA
    - OBJECTS-REMOVE-CHANNEL-METADATA
    - OBJECTS-GET-MEMBERSHIPS-V2
    - OBJECTS-SET-MEMBERSHIPS-V2
    - OBJECTS-REMOVE-MEMBERSHIPS-V2
    - OBJECTS-GET-CHANNEL-MEMBERS-V2
    - OBJECTS-SET-CHANNEL-MEMBERS-V2
    - OBJECTS-REMOVE-CHANNEL-MEMBERS-V2
    - OBJECTS-MANAGE-MEMBERSHIPS-V2
    - OBJECTS-MANAGE-CHANNEL-MEMBERS-V2
  files:
    - FILES-DELETE-FILE
    - FILES-DOWNLOAD-FILE
    - FILES-GET-FILE-URL
    - FILES-LIST-FILES
    - FILES-SEND-FILE
  unsubscribe:
    - UNSUBSCRIBE-ALL
    - UNSUBSCRIBE-SUPPRESS-LEAVE-EVENTS
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE
  others:
    - TELEMETRY
    - QUERY-PARAM
    - PN-OTHER-PROCESSING
    - CREATE-PUSH-PAYLOAD
supported-platforms:
  - version: PubNub Kotlin SDK
    platforms:
      - Windows 10 (8u51 and above)
      - Windows 8.x (Desktop)
      - Windows 7 SP1
      - Windows Vista SP2
      - Windows Server 2008 R2 SP1 (64-bit)
      - Windows Server 2012 and 2012 R2 (64-bit)
      - Intel-based Mac running Mac OS X 10.8.3+, 10.9+
      - Oracle Linux 5.5+
      - Oracle Linux 6.x
      - Oracle Linux 7.x (64-bit) (8u20 and above)
      - Red Hat Enterprise Linux 5.5+, 6.x
      - Red Hat Enterprise Linux 7.x (64-bit) (8u20 and above)
      - Suse Linux Enterprise Server 10 SP2+, 11.x
      - Suse Linux Enterprise Server 12.x (64-bit) (8u31 and above)
      - Ubuntu Linux 12.04 LTS, 13.x
      - Ubuntu Linux 14.x (8u25 and above)
      - Ubuntu Linux 15.04 (8u45 and above)
      - Ubuntu Linux 15.10 (8u65 and above)
    editors:
      - Java8+
  - version: PubNub Android SDK
    platforms:
      - Android 2.3.1+
