/**
 * 
 * Generators for keys, key pairs and password based encryption algorithms.
 */
package org.bouncycastle.crypto.generators;


/**
 *  Generator for MGF1 as defined in PKCS 1v2
 */
public class MGF1BytesGenerator implements org.bouncycastle.crypto.DerivationFunction {

	/**
	 *  @param digest the digest to be used as the source of generated bytes
	 */
	public MGF1BytesGenerator(org.bouncycastle.crypto.Digest digest) {
	}

	public void init(org.bouncycastle.crypto.DerivationParameters param) {
	}

	/**
	 *  return the underlying digest.
	 */
	public org.bouncycastle.crypto.Digest getDigest() {
	}

	/**
	 *  fill len bytes of the output buffer with bytes generated from
	 *  the derivation function.
	 * 
	 *  @throws DataLengthException if the out buffer is too small.
	 */
	public int generateBytes(byte[] out, int outOff, int len) {
	}
}
