jdk: oraclejdk8
language: java
dist: trusty
os: linux


before_install:
  - wget https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.0/codacy-coverage-reporter-2.0.0-assembly.jar

install: skip


stages:
  - name: "test"

jobs:
  include:
    - stage: "test"
      name: "Build & test"
      script: 
        - ./gradlew assemble
        - ./gradlew check
      after_success:
        - java -cp ~/codacy-coverage-reporter-2.0.0-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
