name: pubnub-js-matchmaking
version: 0.11.6
scm: github.com/pubnub/kotlin
schema: 1
files:
  - lib/dist/index.js
changelog:
  - date: 2025-03-26
    version: v0.1.0
    changes:
      - type: feature
        text: "Initial release."
