// release script on github call "build" defined in package.json that in turn call this file that created two distribution cjs and esm
import pkg from "./package.json" assert { type: "json" }
import terser from "@rollup/plugin-terser"

export default [
  {
    input: "../build/packages/js/pubnub-pubnub-matchmaking-kotlin.mjs", // generated by kotlinJS
    external: ["pubnub", "format-util"],
    output: [
      {
        file: pkg.main,
        format: "cjs",
      },
      {
        file: pkg.module,
        format: "esm",
      },
    ],
    plugins: [
      terser()
    ],
  },
]
