name: Just a test

on:
  pull_request:
    types: [ synchronize ]

jobs:
  check-release:
    name: Check release required
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && endsWith(github.repository, '-private') != true }}
    outputs:
      release: ${{ steps.check.outputs.ready }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: check
        name: Check pre-release completed
        uses: ./.github/.release/actions/actions/checks/release
        with:
          token: ${{ secrets.GH_TOKEN }}
  read-info:
    name: Reads info
    runs-on: ubuntu-latest
    outputs:
      productName: ${{ steps.read.outputs.productName }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: read_release_artifact
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: read
        name: Read release info
        uses: ./.github/.release/actions/actions/helpers/read-release-artifact
        with:
          token: ${{ secrets.GH_TOKEN }}
          pr-number: ${{ github.event.number }}
      - name: Publish to maven local
        env:
          product-path: ${{ steps.read.outputs.productPath }}
          token: ${{ secrets.GH_TOKEN }}
          nexus-username: ${{ secrets.NEXUS_USERNAME }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key-name: ${{ secrets.GPG_KEY_NAME }}
          gpg-key-passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
        run:
          export PRODUCT_PATH=`echo ${{ product-path }} | cut -c3-`
          echo $PRODUCT_PATH
          ./gradlew :$PRODUCT_PATH:publishToMavenLocal --no-daemon --no-parallel
          ls -la ~/.m2/repository/com/pubnub/