name: JS automated product release

on:
  pull_request:
    branches: [master]
    types: [closed]
    paths:
      - 'js-chat/.pubnub.yml'

jobs:
  check-release:
    name: Check release required
    if: github.event.pull_request.merged && endsWith(github.repository, '-private') != true
    runs-on:
      group: macos-gh
    outputs:
      release: ${{ steps.check.outputs.ready }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: check
        name: Check pre-release completed
        uses: ./.github/.release/actions/actions/checks/release
        with:
          token: ${{ secrets.GH_TOKEN }}
  publish:
    name: Publish package
    needs: check-release
    if: needs.check-release.outputs.release == 'true'
    runs-on:
      group: macos-gh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
          submodules: recursive
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Publish to NPM
        uses: ./.github/.release/actions/actions/services/npm
        with:
          token: ${{ secrets.GH_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          check-ownership: false
          package-path: package.json
          actions: "build,publish"
          build-command: npm run build
          build-path: dist
          last-service: true
