name: Validations

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  pubnub-yml:
    name: "Validate .pubnub.yml"
    runs-on:
      group: macos-gh
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Checkout validator action
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: "Run '.pubnub.yml' file validation"
        uses: ./.github/.release/actions/actions/validators/pubnub-yml
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  build-validation:
    name: Validate build
    runs-on:
      group: macos-gh
    steps:
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "21"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Validate clean build
        run: ./gradlew ktlintFormat publishAllPublicationsToRepoRepository -PRELEASE_SIGNING_ENABLED=false
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  all-validations:
    name: Validations
    needs: [pubnub-yml, build-validation]
    runs-on:
      group: macos-gh
    steps:
      - name: Validations summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll validations passed"
