name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Build and run tests
        run: |
          ./gradlew assemble
          ./gradlew check
      - name: Validate clean build
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
        run: |
          ./gradlew clean build
  acceptance:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: deployment-tools
      - name: Run mock server action
        uses: ./deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Run acceptance tests (optional)
        run: |
          export pubKey=somePubKey
          export subKey=someSubKey
          export pamPubKey=somePamPubKey
          export pamSubKey=somePamSubKey
          export pamSecKey=someSecKey
          export serverHostPort=localhost:8090
          export serverMock=true
          ./gradlew cucumber --tests RunBetaCucumberTest  -Dcucumber.features="sdk-specifications/features/" -i
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: |
          export pubKey=somePubKey
          export subKey=someSubKey
          export pamPubKey=somePamPubKey
          export pamSubKey=somePamSubKey
          export pamSecKey=someSecKey
          export serverHostPort=localhost:8090
          export serverMock=true
          ./gradlew cucumber --tests RunMainCucumberTest  -Dcucumber.features="sdk-specifications/features/" -i
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports
          path: ./build/reports/cucumber-reports
          retention-days: 7
