name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on:
      group: Default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build and run tests
        run: |
          ./gradlew check
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  acceptance-tests:
    name: Acceptance tests
    runs-on:
      group: Default
    env:
      pubKey: somePubKey
      subKey: someSubKey
      pamPubKey: somePamPubKey
      pamSubKey: somePamSubKey
      pamSecKey: someSecKey
      serverHostPort: "localhost:8090"
      serverMock: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Checkout mock-server action
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Run mock server action
        uses: ./.github/.release/actions/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run acceptance tests (optional)
        run: |
          ln -s /home/runner/work/kotlin/kotlin/sdk-specifications pubnub-kotlin-core/core-impl/src/test/resources/sdk-specifications
          ./gradlew cucumber --tests RunBetaCucumberTest -Dcucumber.features="../../sdk-specifications/features/" -i
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: ./gradlew cucumber --tests RunMainCucumberTest -Dcucumber.features="../../sdk-specifications/features/" -i
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: acceptance-test-reports
          path: ./build/reports/cucumber-reports
          retention-days: 7
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  all-tests:
    name: Tests
    needs: [tests, acceptance-tests]
    runs-on:
      group: Default
    steps:
      - name: Tests summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll tests successfully passed"
