name: Acceptance tests

on: [push]

jobs:
  build:
    name: Perform Acceptance BDD tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: client-engineering-deployment-tools
      - name: Run mock server action
        uses: ./client-engineering-deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run acceptance tests (optional)
        run: |
          export pubKey=somePubKey
          export subKey=someSubKey
          export pamPubKey=somePamPubKey
          export pamSubKey=somePamSubKey
          export pamSecKey=someSecKey
          export serverHostPort=localhost:8090
          export serverMock=true
          export dataFileLocation=src/test/resources/sdk-specifications/features/data
          ln -s /home/runner/work/java/java/sdk-specifications src/test/resources/sdk-specifications
          ./gradlew cucumber --tests RunBetaCucumberTest  -Dcucumber.features="sdk-specifications/features/" -i
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: |
          export pubKey=somePubKey
          export subKey=someSubKey
          export pamPubKey=somePamPubKey
          export pamSubKey=somePamSubKey
          export pamSecKey=someSecKey
          export serverHostPort=localhost:8090
          export serverMock=true
          export dataFileLocation=src/test/resources/sdk-specifications/features/data
           ln -s /home/runner/work/java/java/sdk-specifications src/test/resources/sdk-specifications
          ./gradlew cucumber --tests RunMainCucumberTest  -Dcucumber.features="sdk-specifications/features/" -i
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports
          path: ./build/reports/cucumber-reports
          retention-days: 7
